### ISSUE TITLE
Execute configurable commands on infraction create

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#10]
**Disconnection issue**
I noticed with Refractor it has random disconnections, it re-connects back after a few seconds or a bit longer. I will change rcon time-out in `game.ini` file to a longer time and will post back if that fixed or not.

**Feature requests / rework**
1. Warn log > When you warn a player on Refractor that it uses a server message like `[Server]:{{PLAYER_NAME}} Has been warned by {{ADMIN.NAME}}. Reason: {{REASON}}`
2. Kick log > Kicks the player from the server | `{{ADMIN.NAME}} Has kicked you out the server. Reason: {{REASON}}`
3. Mute > That it also mutes in-game, currently this is not a feature but a logging system(also an option to unmute a player and sync it like the ban system).
4. Ban > Currently this only works when the person enters the server. Would be nice if this kicks the player immediately out of the server and add an option to unban the person.

**Comment by sniddunc** [comment]
Hi @Deathay, changing the Mordhau Game.ini RconTimeout to a higher value (I would suggest 2147483646) should resolve the disconnection issues. If it does not, please open a second issue so I can properly file and reference it as a bug.

I like the suggested reworks. I think the way I'll accomplish this is by reworking the game command configuration so that you can define commands to be run on the creation of infractions.

For example, when creating a mute you could tell the server to run `Mute {{PLAYER_ID}} {{DURATION}}` as well as `Say {{PLAYER_NAME}} was muted`. This should provide much more flexibility by letting server owners customize the exact behavior they want.

As for the last part of number 4 in your list (unbanning), this will likely require a bit more work. Refractor has functionality where you can repeal and delete infractions. I could add customizable commands to be executed on repeals and deletes like on creation, though this will likely take a little longer to implement.

Thanks for the suggestions! If you have any thoughts on the implementation outlined above, please let me know.

**Comment by Deathay** [comment]
Hey, i also like the ideas what you have said above. How more customized for server owners, the better Refractor will be 👍.
Currently also Mordhau displays when a person gets muted in a Server message, so that one wouldn't be needed(although i could be wrong about it in RCON).

Thanks for making this public, really useful.

**Comment by Deathay** [comment]
Hey @sniddunc, the disconnections has been solved with changing the `RconTimeout=120.000000` to `RconTimeout=2147483646`.

Thanks!

**Comment by sniddunc** [comment]
Configurable infraction event commands have been added in Refractor version 0.2.0 and Refractor-Svelte v0.2.0. These features were thoroughly tested, but should still be considered experimental. Closing this issue.
