### ISSUE TITLE
Sync ban issue

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#30]
Hey,

When banning or muting a player PERMANENT it does not sync. It only works on the server where you created the ban/mute.

Thanks for the v0.3.0 release :)

**Comment by sniddunc** [comment]
This is a symptom of a larger issue, unfortunately. The duration value for permanent infractions is 0. When the duration check is done to determine if the ban should be synced, it gets ignored since the duration of the ban is 0.

This will take a pretty large refactor, but we should switch away from using 0 as the permanent value anyway.

**Comment by sniddunc** [comment]
Resolved in release v0.3.1
