### ISSUE TITLE
Player name color by infraction

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#35]
Hey, when using the Refresh button [screen](https://i.imgur.com/Z6CClA8.png) the colors of infractions dissapears, you have to use F5(refresh webpage) to see them back.

**Comment by sniddunc** [comment]
Each time I add a stat field on a player, I need to adjust all sources which send player data to include this new field. We now have 3 or more places where this player info is sourced from, so this is likely caused by me forgetting to update one of them.

I will do a refactor to make a single source for player info. Thanks for reporting this.

**Comment by sniddunc** [comment]
Resolved in release v0.3.2
