### ISSUE TITLE
Force Refresh playerlist

### ISSUE THREAD

**Issue by Deathay** [RefractorGSCM/Refractor#50]
Hey, 

Earlier i made a bug report about the playerlist refresh. I just noticed if the other user does not have administrator rights(in group settings), it will not have the option to refresh the playerlist.

**Comment by sniddunc** [comment]
That is by design. Refractor does a good job of maintaining the active player list without the need for manual refreshes. Manual refreshes are intended for restoring the player list when some server critical event happens where a server is no longer able to send player quit broadcasts, for example a server crash.

There should not be need to manually refresh the player list in any other case, so this ability is restricted to admins as it is a somewhat expensive operation.
